/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab8p2_ricardoquiroz;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author rjqer
 */
public class MainGintama extends javax.swing.JFrame {

    /**
     * Creates new form MainGintama
     */
    public MainGintama() {
        initComponents();       
    }
    
    public void adminUni(String path){
        archivoU = new File(path);
    }
    
    public void  adminSV(String path){
        archivoSV = new File(path); 
    }   
    
    public void Cargaruniversos(){
        try {
            listaU = new ArrayList();
            Universo temp;
            if (archivoU.exists()) {
                FileInputStream enter = new FileInputStream(archivoU);
                ObjectInputStream object = new ObjectInputStream(enter);
                try {
                    while ((temp = (Universo)object.readObject()) != null) {                        
                        listaU.add(temp);
                    }
                } catch (Exception e) {
                }
                object.close();
                enter.close();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void Cargarseres(){
        try {
            listaSV = new ArrayList();
            SerVivo temp;
            if (archivoSV.exists()) {
                FileInputStream enter = new FileInputStream(archivoSV);
                ObjectInputStream object = new ObjectInputStream(enter);
                try {
                    while ((temp = (SerVivo)object.readObject()) != null) {                        
                        listaSV.add(temp);
                    }
                } catch (Exception e) {
                }
                object.close();
                enter.close();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void Escribiruniversos(){
        FileOutputStream fos = null;
        ObjectOutputStream oos = null;
        try {
            fos = new FileOutputStream(archivoU);
            oos = new ObjectOutputStream(fos);
            for (Universo universo : listaU) {
                oos.writeObject(universo);
            }
            oos.flush();
        } catch (Exception e) {
        }
        finally{
            try {
                oos.close();
                fos.close();
            } catch (Exception e) {
            }
        }
    }
    
    public void Escribirseres(){
        FileOutputStream fos = null;
        ObjectOutputStream oos = null;
        try {
            fos = new FileOutputStream(archivoSV);
            oos = new ObjectOutputStream(fos);
            for (SerVivo sv : listaSV) {
                oos.writeObject(sv);
            }
            oos.flush();
        } catch (Exception e) {
        }
        finally{
            try {
                oos.close();
                fos.close();
            } catch (Exception e) {
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        TF_nombreUni = new javax.swing.JTextField();
        JB_crearuniverso = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TF_nombreSer = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TF_id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JS_poder = new javax.swing.JSpinner();
        JS_anios = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        CB_universoproc = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        RB_humano = new javax.swing.JRadioButton();
        RB_amanto = new javax.swing.JRadioButton();
        JB_crearpersona = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        TF_nombreSer1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TF_id1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        JS_poder1 = new javax.swing.JSpinner();
        JS_anios1 = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        CB_universoproc1 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        RB_humano1 = new javax.swing.JRadioButton();
        RB_amanto1 = new javax.swing.JRadioButton();
        JB_modpersona = new javax.swing.JButton();
        CB_modificar = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        CB_eliminarser = new javax.swing.JComboBox<>();
        JB_eliminarser = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        TF_busquedanombre = new javax.swing.JTextField();
        TF_busquedaid = new javax.swing.JTextField();
        JB_busqueda = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        JB_cargararchivo = new javax.swing.JButton();
        JB_guardararchivo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        PB_barraarchivo = new javax.swing.JProgressBar();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel8.setText("Nombre");

        JB_crearuniverso.setText("Crear Universo");
        JB_crearuniverso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_crearuniversoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel8)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JB_crearuniverso, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                    .addComponent(TF_nombreUni))
                .addContainerGap(609, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TF_nombreUni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(JB_crearuniverso)
                .addContainerGap(385, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("CrearUniverso", jPanel1);

        jLabel2.setText("Nombre");

        jLabel3.setText("ID");

        jLabel4.setText("Poder");

        jLabel5.setText("Años");

        jLabel6.setText("Universo de Procedencia");

        jLabel7.setText("Raza");

        buttonGroup1.add(RB_humano);
        RB_humano.setText("Humano");

        buttonGroup1.add(RB_amanto);
        RB_amanto.setText("Amanto");

        JB_crearpersona.setText("Crear Persona");
        JB_crearpersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_crearpersonaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TF_nombreSer)
                    .addComponent(TF_id)
                    .addComponent(JS_poder, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(JS_anios))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(RB_humano)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RB_amanto))
                            .addComponent(CB_universoproc, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(JB_crearpersona, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TF_nombreSer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(CB_universoproc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TF_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(RB_humano)
                    .addComponent(RB_amanto))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(JS_poder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(JS_anios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(JB_crearpersona, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(321, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("CrearSerVivo", jPanel2);

        jLabel9.setText("Nombre");

        jLabel10.setText("ID");

        jLabel11.setText("Poder");

        jLabel12.setText("Años");

        jLabel13.setText("Universo de Procedencia");

        jLabel14.setText("Raza");

        buttonGroup2.add(RB_humano1);
        RB_humano1.setSelected(true);
        RB_humano1.setText("Humano");

        buttonGroup2.add(RB_amanto1);
        RB_amanto1.setText("Amanto");

        JB_modpersona.setText("Modificar Persona");
        JB_modpersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_modpersonaMouseClicked(evt);
            }
        });

        CB_modificar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CB_modificarItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CB_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TF_nombreSer1)
                            .addComponent(TF_id1)
                            .addComponent(JS_poder1)
                            .addComponent(JS_anios1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addComponent(JB_modpersona, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13))
                                .addGap(52, 52, 52)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(RB_humano1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(RB_amanto1))
                                    .addComponent(CB_universoproc1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(CB_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(TF_nombreSer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(CB_universoproc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(TF_id1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(RB_humano1)
                    .addComponent(RB_amanto1))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(JS_poder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(JS_anios1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(JB_modpersona, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(173, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ModSerVivo", jPanel3);

        JB_eliminarser.setText("Eliminar del Sistema");
        JB_eliminarser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_eliminarserMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(CB_eliminarser, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(JB_eliminarser, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(258, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(CB_eliminarser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160)
                .addComponent(JB_eliminarser, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("EliminarSerVivo", jPanel4);

        jLabel16.setText("Nombre");

        jLabel17.setText("ID");

        JB_busqueda.setText("Realizar Busqueda");
        JB_busqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_busquedaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JB_busqueda, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TF_busquedanombre, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                        .addComponent(TF_busquedaid)))
                .addContainerGap(497, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(TF_busquedanombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(TF_busquedaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(JB_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(303, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("BusquedaSerVivo", jPanel5);

        JB_cargararchivo.setText("Cargar Archivo");
        JB_cargararchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_cargararchivoMouseClicked(evt);
            }
        });

        JB_guardararchivo.setText("Guardar Archivo");
        JB_guardararchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_guardararchivoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(370, 370, 370)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JB_guardararchivo, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(JB_cargararchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(407, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(JB_cargararchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(JB_guardararchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(295, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cargar/GuardarArchivo", jPanel6);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Sistema de Control");

        PB_barraarchivo.setStringPainted(true);

        jLabel15.setText("Carga:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PB_barraarchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PB_barraarchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel15)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_crearuniversoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_crearuniversoMouseClicked
        // TODO add your handling code here:
        Universo univ = new Universo(TF_nombreUni.getText());
        listaU.add(univ);
        DefaultComboBoxModel mod = (DefaultComboBoxModel)CB_universoproc.getModel();
        mod.removeAllElements();
        for (Universo u : listaU) {
            mod.addElement(u);
        }
        DefaultComboBoxModel modelo = (DefaultComboBoxModel)CB_universoproc1.getModel();
        modelo.removeAllElements();
        for (Universo universo : listaU) {
            modelo.addElement(universo);
        }
        JOptionPane.showMessageDialog(this, "Universo creado exitosamente");
        TF_nombreUni.setText("");
    }//GEN-LAST:event_JB_crearuniversoMouseClicked

    private void JB_crearpersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_crearpersonaMouseClicked
        // TODO add your handling code here:
        String raza;
        try {
            JOptionPane.showMessageDialog(this, "No se puede crear");
        } catch (Exception e) {
        }
        if (RB_humano.isSelected()) {
            raza = "Humano";
        }
        else{
            raza = "Amanto";
        }
        SerVivo serv = new SerVivo(TF_nombreSer.getText(), TF_id.getText(), ((Universo)CB_universoproc.getSelectedItem()).getNombre(), raza, (Integer)JS_poder.getValue(), (Integer)JS_anios.getValue());
        listaSV.add(serv);
        DefaultComboBoxModel mod = (DefaultComboBoxModel)CB_modificar.getModel();
        mod.removeAllElements();
        for (SerVivo sv : listaSV) {
            mod.addElement(sv);
        }
        DefaultComboBoxModel modelo = (DefaultComboBoxModel)CB_eliminarser.getModel();
        modelo.removeAllElements();
        for (SerVivo ser : listaSV) {
            modelo.addElement(ser);
        }
        JOptionPane.showMessageDialog(this, "Ser Vivo creado exitosamente");
        TF_nombreSer.setText("");
        TF_id.setText("");
    }//GEN-LAST:event_JB_crearpersonaMouseClicked

    private void JB_modpersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_modpersonaMouseClicked
        // TODO add your handling code here:
        String raza;
        if (RB_humano.isSelected()) {
            raza = "Humano";
        }
        else{
            raza = "Amanto";
        }
        SerVivo serv = new SerVivo(TF_nombreSer.getText(), TF_id.getText(), ((Universo)CB_universoproc.getSelectedItem()).getNombre(), raza, (Integer)JS_poder.getValue(), (Integer)JS_anios.getValue());
        listaSV.remove((SerVivo)CB_modificar.getSelectedItem());
        listaSV.add(serv);
        DefaultComboBoxModel mod = (DefaultComboBoxModel)CB_modificar.getModel();
        mod.removeAllElements();
        for (SerVivo sv : listaSV) {
            mod.addElement(sv);
        }
        DefaultComboBoxModel modelo = (DefaultComboBoxModel)CB_eliminarser.getModel();
        modelo.removeAllElements();
        for (SerVivo ser : listaSV) {
            modelo.addElement(ser);
        }
        JOptionPane.showMessageDialog(this, "Ser Vivo modificado exitosamente");
        
    }//GEN-LAST:event_JB_modpersonaMouseClicked

    private void CB_modificarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CB_modificarItemStateChanged
        // TODO add your handling code here:
        SerVivo temp = (SerVivo)CB_modificar.getSelectedItem();
        if (temp != null) {
            TF_nombreSer1.setText(temp.getNombre());
            TF_id1.setText(temp.getId());
            JS_poder1.setValue(temp.getPoder());
            JS_anios1.setValue(temp.getAnios());
            CB_universoproc1.setSelectedItem(temp.getUnivesoproc());
//            if (temp.getRaza() == "Humano") {
//                RB_humano1.isEnabled();
//            }
//            else{
//                RB_amanto1.isEnabled();
//            }
        }
        
    }//GEN-LAST:event_CB_modificarItemStateChanged

    private void JB_eliminarserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_eliminarserMouseClicked
        // TODO add your handling code here:
        listaSV.remove((SerVivo)CB_eliminarser.getSelectedItem());
        DefaultComboBoxModel mod = (DefaultComboBoxModel)CB_modificar.getModel();
        mod.removeAllElements();
        for (SerVivo sv : listaSV) {
            mod.addElement(sv);
        }
        DefaultComboBoxModel modelo = (DefaultComboBoxModel)CB_eliminarser.getModel();
        modelo.removeAllElements();
        for (SerVivo ser : listaSV) {
            modelo.addElement(ser);
        }
        JOptionPane.showMessageDialog(this, "Ser Vivo eliminado exitosamente");
    }//GEN-LAST:event_JB_eliminarserMouseClicked

    private void JB_busquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_busquedaMouseClicked
        // TODO add your handling code here:
        String nombre = TF_busquedanombre.getText();
        String id = TF_busquedaid.getText();
        for (SerVivo sv : listaSV) {
            if (nombre.equals(sv.getNombre()) && id.equals(sv.getId())) {
                JOptionPane.showMessageDialog(this, "Si esta registrado");
            }
            else{
                JOptionPane.showMessageDialog(this, "No esta registrado");
            }
        }
        
    }//GEN-LAST:event_JB_busquedaMouseClicked

    private void JB_cargararchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_cargararchivoMouseClicked
        // TODO add your handling code here:
        //Cargar los archivos
//        adminUni("./labcarpetas");
//        adminSV("./labcarpetas");
        try {
                Barra bar = new Barra(PB_barraarchivo, listaSV);
                bar.start();
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_JB_cargararchivoMouseClicked

    private void JB_guardararchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_guardararchivoMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_JB_guardararchivoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGintama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGintama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGintama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGintama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGintama().setVisible(true);
            }
        });
    }
    
    private File archivoU = null;
    private File archivoSV = null;
    private ArrayList<Universo> listaU = new ArrayList();
    private ArrayList<SerVivo> listaSV = new ArrayList();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CB_eliminarser;
    private javax.swing.JComboBox<String> CB_modificar;
    private javax.swing.JComboBox<String> CB_universoproc;
    private javax.swing.JComboBox<String> CB_universoproc1;
    private javax.swing.JButton JB_busqueda;
    private javax.swing.JButton JB_cargararchivo;
    private javax.swing.JButton JB_crearpersona;
    private javax.swing.JButton JB_crearuniverso;
    private javax.swing.JButton JB_eliminarser;
    private javax.swing.JButton JB_guardararchivo;
    private javax.swing.JButton JB_modpersona;
    private javax.swing.JSpinner JS_anios;
    private javax.swing.JSpinner JS_anios1;
    private javax.swing.JSpinner JS_poder;
    private javax.swing.JSpinner JS_poder1;
    private javax.swing.JProgressBar PB_barraarchivo;
    private javax.swing.JRadioButton RB_amanto;
    private javax.swing.JRadioButton RB_amanto1;
    private javax.swing.JRadioButton RB_humano;
    private javax.swing.JRadioButton RB_humano1;
    private javax.swing.JTextField TF_busquedaid;
    private javax.swing.JTextField TF_busquedanombre;
    private javax.swing.JTextField TF_id;
    private javax.swing.JTextField TF_id1;
    private javax.swing.JTextField TF_nombreSer;
    private javax.swing.JTextField TF_nombreSer1;
    private javax.swing.JTextField TF_nombreUni;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
